# Predict pipeline WITHOUT reference graph.
step0:
  attribute: G_shap
  method: shaps.predict
step1:
  attribute: prior
  method: get_prior_from_ref_graph
  arguments:
    ref_graph: ref_graph
step2:
  attribute: G_prior
  method: shaps.predict
  arguments:
    prior: prior
step3:
  attribute: G_rho
  method: dag_from_discrepancy
