DEFAULT_ITERATIVE_TRIALS: int = 20
DEFAULT_HPO_TRIALS: int = 20
DEFAULT_BOOTSTRAP_TRIALS: int = 20
DEFAULT_BOOTSTRAP_TOLERANCE: float = 0.3
DEFAULT_BOOTSTRAP_SAMPLING_SPLIT: float = 0.2
DEFAULT_SEED: int = 42

DEFAULT_REGRESSORS = ['nn', 'gbt']
