# Generated by CodiumAI
from causalgraph.common.utils import select_device


import pytest

# Tests that the function returns 'cuda' when force is 'cuda' and cuda is available
def test_returns_cuda_when_force_is_cuda_and_cuda_is_not_available():
    # Try to force cuda when cuda is not available
    # Should raise a ValueError
    with pytest.raises(ValueError):
        select_device(force='cuda')

# Tests that the function returns 'mps' when force is 'mps' and mps is available
def test_returns_mps_when_force_is_mps_and_mps_is_available():
    result = select_device(force='mps')
    assert result == 'mps'

# Tests that the function returns 'cpu' when force is 'cpu' and no other options are available
def test_returns_cpu_when_force_is_cpu_and_no_other_options_are_available():
    result = select_device(force='cpu')
    assert result == 'cpu'

# Tests that the function returns 'mps' when mps is available and no force is specified
def test_returns_mps_when_mps_is_available_and_no_force_is_specified():
    result = select_device()
    assert result == 'mps'

# Tests that the function returns 'cpu' when no other options are available and no force is specified
def test_returns_cpu_when_no_other_options_are_available_and_no_force_is_specified():
    result = select_device()
    assert result == 'mps'