name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - closed
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - '.github/workflows/docs.yaml'
      - 'LICENSE'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests and collect coverage
        run: |
          pip install rich
          pip install pytest
          pip install pytest-cov
          pytest --cov .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: renero/causalgraph

      - name: Install dependencies for publishing
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PUBLISHING_TOKEN }}
        run: |
          twine upload dist/* --verbose
        if: |
          (github.event_name == 'push') ||
          (github.event_name == 'push' && contains(github.event.head_commit.message, 'Merge branch ''develop''')) ||
          (github.event_name == 'pull_request' && github.event.pull_request.merged == true && 
           github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'develop')
