name: Causal-graph repo
on: [push, pull_request]
jobs:
  runs-on: ${{ matrix.os }}
  run:
  - name: Upload coverage reports to Codecov
    uses: codecov/codecov-action@v4.0.1
    with:
      token: ${{ secrets.CODECOV_TOKEN }}
      slug: renero/causal-graph
